import { useState } from "react";
import { AlertTriangle, Check, CircleCheck, ExternalLink, Filter, RotateCcw, SlidersHorizontal, X } from "lucide-react";
import { Link } from "react-router-dom";
import { useApp } from "../app/AppProvider";
import { environments } from "../data/mockData";
import type { AlertStatus } from "../domain/types";
import { formatDateTime } from "../utils/format";

const statusLabel: Record<AlertStatus, string> = { new: "Nueva", acknowledged: "Reconocida", closed: "Cerrada" };

export function AlertsPage() {
  const { alerts, setAlertStatus } = useApp();
  const [filter, setFilter] = useState<"all" | AlertStatus>("all");
  const visible = filter === "all" ? alerts : alerts.filter((alert) => alert.status === filter);
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Avisos del hogar</p><h1 className="page-title mt-2">Alertas simuladas</h1><p className="mt-3 text-slate-600">Reconoce y cierra alertas localmente. Los cambios se guardan en este navegador.</p></div><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white p-1"><Filter className="ml-2 h-4 w-4 text-slate-500"/><label className="sr-only" htmlFor="alert-filter">Filtrar alertas</label><select id="alert-filter" className="border-0 bg-transparent py-2 pr-3 text-sm font-bold" value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)}><option value="all">Todas</option><option value="new">Nuevas</option><option value="acknowledged">Reconocidas</option><option value="closed">Cerradas</option></select></div></header>
    <div className="grid gap-4 sm:grid-cols-3">{(["new","acknowledged","closed"] as AlertStatus[]).map((status) => <button key={status} onClick={() => setFilter(status)} className={`panel flex items-center justify-between p-4 text-left transition hover:border-forest-200 ${filter === status ? "ring-2 ring-forest-500" : ""}`}><span><span className="block text-2xl font-bold">{alerts.filter((alert) => alert.status === status).length}</span><span className="text-sm text-slate-500">{statusLabel[status]}{status === "new" ? "s" : "s"}</span></span>{status === "new" ? <AlertTriangle className="text-danger-500"/> : status === "acknowledged" ? <Check className="text-amber-700"/> : <CircleCheck className="text-forest-600"/>}</button>)}</div>
    {visible.length === 0 ? <div className="panel grid min-h-52 place-items-center p-6 text-center"><div><CircleCheck className="mx-auto h-8 w-8 text-forest-600"/><h2 className="mt-3 font-bold">No hay alertas en este estado</h2><p className="mt-1 text-sm text-slate-500">Selecciona otro filtro para continuar.</p></div></div> : <div className="space-y-4" aria-live="polite">{visible.map((alert) => { const environment = environments.find((item) => item.id === alert.environmentId); return <article key={alert.id} className={`panel border-l-4 p-4 sm:p-5 ${alert.status === "closed" ? "border-l-slate-300" : alert.severity === "critical" ? "border-l-danger-500" : "border-l-amber-500"}`}><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div className="min-w-0 max-w-3xl"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${alert.status === "new" ? "bg-danger-50 text-danger-700" : alert.status === "acknowledged" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{statusLabel[alert.status]}</span><span className="text-xs font-semibold text-slate-500">{environment?.name ?? "Zona simulada"} · {formatDateTime(alert.openedAt)}</span></div><h2 className="mt-3 text-lg font-bold">{alert.title}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{alert.description}</p><div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm leading-6"><strong>Recomendación:</strong> {alert.recommendation}</div></div><div className="grid w-full shrink-0 grid-cols-2 gap-2 sm:flex sm:flex-wrap xl:w-auto xl:justify-end">{alert.status === "new" && <button className="button-secondary w-full sm:w-auto" onClick={() => setAlertStatus(alert.id, "acknowledged")}><Check className="h-4 w-4"/>Reconocer</button>}{alert.status !== "closed" && <button className="button-secondary w-full sm:w-auto" onClick={() => setAlertStatus(alert.id, "closed")}><X className="h-4 w-4"/>Cerrar</button>}{alert.status === "closed" && <button className="button-secondary w-full sm:w-auto" onClick={() => setAlertStatus(alert.id, "new")}><RotateCcw className="h-4 w-4"/>Reabrir</button>}<Link className="button-secondary w-full sm:w-auto" to={`/dashboard/ambientes/${alert.environmentId}`}><ExternalLink className="h-4 w-4"/>Ver detalle</Link>{alert.type === "potential-waste" || alert.type === "energy" || alert.type === "lighting" ? <Link className="button-primary col-span-2 w-full sm:w-auto" to="/simulador"><SlidersHorizontal className="h-4 w-4"/>Aplicar en simulador</Link> : null}</div></div></article>})}</div>}
  </div>;
}
