import { Activity, AlertTriangle, Bolt, Leaf, PiggyBank, RadioTower, WifiOff } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "react-router-dom";
import { useApp } from "../app/AppProvider";
import { ChartFrame } from "../components/ChartFrame";
import { Disclaimer } from "../components/Disclaimer";
import { ErrorState, LoadingState } from "../components/LoadingState";
import { MetricCard } from "../components/MetricCard";
import { StatusBadge } from "../components/StatusBadge";
import { useDashboardData } from "../hooks/useEcoData";
import { formatNumber } from "../utils/format";

const hourlyData = [
  { hour: "06:00", watts: 760 }, { hour: "08:00", watts: 430 }, { hour: "10:00", watts: 180 }, { hour: "12:00", watts: 980 }, { hour: "14:00", watts: 310 }, { hour: "16:00", watts: 240 }, { hour: "18:00", watts: 1280 }, { hour: "22:00", watts: 390 },
];
const dailyData = [
  { day: "Vie", kwh: 8.2 }, { day: "Sáb", kwh: 10.4 }, { day: "Dom", kwh: 9.1 }, { day: "Lun", kwh: 7.8 }, { day: "Mar", kwh: 8.4 }, { day: "Mié", kwh: 7.7 }, { day: "Jue", kwh: 9.3 },
];
const categoryData = [{ name: "Energía", count: 2 }, { name: "Ambiente", count: 2 }, { name: "Conexión", count: 1 }];
const COLORS = ["#16815f", "#e5a30f", "#2a84c6", "#dc594b", "#64748b"];

export function DashboardPage() {
  const { data, error } = useDashboardData();
  const { alerts, config } = useApp();
  if (error) return <ErrorState />;
  if (!data) return <LoadingState />;
  const totalPower = data.snapshots.reduce((sum, item) => sum + item.powerWatts, 0);
  const energy = data.snapshots.reduce((sum, item) => sum + item.energyKwh, 0);
  const potentialEnergy = data.snapshots.filter((item) => !item.presenceDetected && item.powerWatts > config.minimumPowerWatts).reduce((sum, item) => sum + (item.powerWatts * 2 * 30) / 1000, 0);
  const openAlerts = alerts.filter((alert) => alert.status !== "closed");
  const comparison = data.environments.map((environment, index) => ({ name: environment.name.replace(" principal", ""), watts: data.snapshots[index]?.powerWatts ?? 0 }));
  const climate = hourlyData.map((item, index) => ({ hour: item.hour, temperatura: 23.5 + index * .7, humedad: 53 + (index % 3) * 3 }));
  return <div className="space-y-6"><header><p className="eyebrow">Resumen del hogar</p><h1 className="page-title mt-2">Dashboard EcoAhorro</h1><p className="mt-3 text-slate-600">Hogar Eco Tarija · Vivienda familiar · Lecturas y estimaciones del escenario demostrativo.</p></header><Disclaimer />
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-7"><MetricCard label="Consumo actual" value={formatNumber(totalPower, 0)} unit="W" hint="Simulado" icon={Activity} tone="blue" /><MetricCard label="Energía mensual" value={formatNumber(energy)} unit="kWh/mes" hint="Estimada" icon={Bolt} tone="blue" /><MetricCard label="Ahorro potencial" value={formatNumber(potentialEnergy * config.electricityTariffBs)} unit="Bs/mes" hint="No garantizado" icon={PiggyBank} /><MetricCard label="CO₂ evitable" value={formatNumber(potentialEnergy * config.emissionFactorKgPerKwh)} unit="kg CO₂/mes" hint="Estimado" icon={Leaf} /><MetricCard label="Alertas activas" value={openAlerts.length} unit="alertas" icon={AlertTriangle} tone="red" /><MetricCard label="Nodos conectados" value={data.snapshots.filter((item) => item.nodeOnline).length} unit="nodos" icon={RadioTower} /><MetricCard label="Desconectados" value={data.snapshots.filter((item) => !item.nodeOnline).length} unit="nodo" icon={WifiOff} tone="amber" /></section>
    <section className="grid gap-6 lg:grid-cols-2"><ChartFrame title="Consumo por hora" description="Potencia residencial simulada en W"><ResponsiveContainer width="100%" height="100%"><LineChart data={hourlyData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="hour" fontSize={12}/><YAxis fontSize={12} unit=" W" width={62}/><Tooltip/><Line isAnimationActive={false} type="monotone" dataKey="watts" name="Potencia" stroke="#16815f" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></ChartFrame><ChartFrame title="Energía por día" description="Estimación determinista en kWh"><ResponsiveContainer width="100%" height="100%"><BarChart data={dailyData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day" fontSize={12}/><YAxis fontSize={12} unit=" kWh" width={58}/><Tooltip/><Bar isAnimationActive={false} dataKey="kwh" name="Energía" fill="#2a84c6" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></ChartFrame>
      <ChartFrame title="Comparación por zona" description="Potencia actual simulada"><ResponsiveContainer width="100%" height="100%"><BarChart data={comparison} layout="vertical" margin={{ left: 14 }}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" fontSize={12} unit=" W"/><YAxis type="category" dataKey="name" fontSize={11} width={82}/><Tooltip/><Bar isAnimationActive={false} dataKey="watts" name="Potencia" radius={[0,6,6,0]}>{comparison.map((_, index) => <Cell key={index} fill={COLORS[index]} />)}</Bar></BarChart></ResponsiveContainer></ChartFrame><ChartFrame title="Temperatura y humedad" description="Tendencia simulada; escalas distintas"><ResponsiveContainer width="100%" height="100%"><LineChart data={climate}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="hour" fontSize={12}/><YAxis fontSize={12}/><Tooltip/><Legend/><Line isAnimationActive={false} type="monotone" dataKey="temperatura" name="Temperatura °C" stroke="#e5a30f" strokeWidth={2}/><Line isAnimationActive={false} type="monotone" dataKey="humedad" name="Humedad %" stroke="#2a84c6" strokeWidth={2}/></LineChart></ResponsiveContainer></ChartFrame>
      <ChartFrame title="Alertas por categoría" description="Incluye alertas abiertas y cerradas"><ResponsiveContainer width="100%" height="100%"><BarChart data={categoryData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" fontSize={12}/><YAxis allowDecimals={false} fontSize={12}/><Tooltip/><Bar isAnimationActive={false} dataKey="count" name="Alertas" fill="#dc594b" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></ChartFrame><ChartFrame title="Tiempo sin actividad" description="Minutos en el momento de la lectura"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.environments.map((item, i) => ({ name: item.name.split(" ")[0], minutes: data.snapshots[i].minutesWithoutActivity }))}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" fontSize={11}/><YAxis fontSize={12} unit=" min" width={62}/><Tooltip/><Bar isAnimationActive={false} dataKey="minutes" name="Sin actividad" fill="#e5a30f" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></ChartFrame></section>
    <section className="panel overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="text-lg font-bold">Zonas del hogar</h2><p className="text-sm text-slate-500">Última actualización simulada: 28 ago 2026 · 20:30</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["Zona","Estado","Potencia","Actividad","Temperatura","Alertas","Actualización","Acción"].map((heading) => <th key={heading} className="px-5 py-3 font-bold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{data.environments.map((environment, index) => { const snapshot = data.snapshots[index]; return <tr key={environment.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-bold">{environment.name}<span className="block text-xs font-normal text-slate-500">{environment.type}</span></td><td className="px-5 py-4"><StatusBadge status={environment.status} /></td><td className="px-5 py-4 font-semibold">{snapshot.nodeOnline ? `${snapshot.powerWatts} W` : "Sin datos"}</td><td className="px-5 py-4">{snapshot.presenceDetected ? "Detectada" : "No detectada"}</td><td className="px-5 py-4">{snapshot.nodeOnline ? `${snapshot.temperatureCelsius} °C` : "—"}</td><td className="px-5 py-4">{alerts.filter((alert) => alert.environmentId === environment.id && alert.status !== "closed").length}</td><td className="px-5 py-4 text-slate-500">20:30</td><td className="px-5 py-4"><Link className="font-bold text-forest-700 hover:underline" to={`/dashboard/ambientes/${environment.id}`}>Ver detalle</Link></td></tr> })}</tbody></table></div></section>
  </div>;
}
