import { useMemo, useState } from "react";
import { Activity, ArrowLeft, Bolt, Clock3, Droplets, RadioTower, Thermometer, Wind } from "lucide-react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link, useParams } from "react-router-dom";
import { useApp } from "../app/AppProvider";
import { ChartFrame } from "../components/ChartFrame";
import { ErrorState, LoadingState } from "../components/LoadingState";
import { MetricCard } from "../components/MetricCard";
import { StatusBadge } from "../components/StatusBadge";
import { useEnvironmentData } from "../hooks/useEcoData";
import { formatDateTime, formatNumber } from "../utils/format";

export function EnvironmentDetailPage() {
  const { environmentId } = useParams();
  const { data, notFound, error } = useEnvironmentData(environmentId);
  const { alerts, config } = useApp();
  const [period, setPeriod] = useState<"today" | "7" | "30">("7");
  const filteredHistory = useMemo(() => { if (!data) return []; const points = period === "today" ? 6 : period === "7" ? 42 : 180; return data.history.slice(-points); }, [data, period]);
  if (notFound) return <div className="grid min-h-[60vh] place-items-center"><div className="max-w-lg text-center"><p className="eyebrow">Zona no encontrada</p><h1 className="page-title mt-2">No existen datos para esta ruta</h1><p className="mt-3 text-slate-600">Comprueba la zona o regresa al resumen del hogar.</p><Link to="/dashboard" className="button-primary mt-6"><ArrowLeft className="h-4 w-4" />Volver al dashboard</Link></div></div>;
  if (error) return <ErrorState message="La fuente simulada no respondió para esta zona." />;
  if (!data) return <LoadingState />;
  const { environment, snapshot } = data;
  const environmentAlerts = alerts.filter((alert) => alert.environmentId === environment.id);
  const chartData = filteredHistory.map((item) => ({ time: new Intl.DateTimeFormat("es-BO", { day: "2-digit", hour: "2-digit" }).format(new Date(item.recordedAt)), potencia: item.powerWatts, temperatura: item.temperatureCelsius, humedad: item.humidityPercent }));
  const potentialMonthly = (!snapshot.presenceDetected && snapshot.powerWatts > config.minimumPowerWatts) ? (snapshot.powerWatts * 2 * 30) / 1000 : 0;
  return <div className="space-y-6"><Link className="inline-flex items-center gap-2 text-sm font-bold text-forest-700 hover:underline" to="/dashboard"><ArrowLeft className="h-4 w-4" />Todas las zonas</Link><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Detalle de la zona</p><h1 className="page-title mt-2">{environment.name}</h1><p className="mt-2 text-slate-600">{environment.type} · Uso habitual de hasta {environment.occupancyCapacity} personas · Vivienda demostrativa</p></div><StatusBadge status={environment.status} className="self-start sm:self-auto" /></header>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Potencia actual" value={snapshot.nodeOnline ? formatNumber(snapshot.powerWatts) : "—"} unit="W" hint="Origen: simulated" icon={Bolt} tone="blue"/><MetricCard label="Temperatura" value={snapshot.nodeOnline ? snapshot.temperatureCelsius : "—"} unit="°C" hint="Lectura simulada" icon={Thermometer} tone="amber"/><MetricCard label="Humedad" value={snapshot.nodeOnline ? snapshot.humidityPercent : "—"} unit="%" hint="Humedad relativa" icon={Droplets} tone="blue"/><MetricCard label="Cambio del aire" value={snapshot.nodeOnline ? snapshot.airChangePercent : "—"} unit="%" hint="Respecto a línea base simulada; no ppm" icon={Wind} /></section>
    <section className="grid gap-6 xl:grid-cols-[1fr_320px]"><div><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Historial de mediciones</h2><p className="text-xs text-slate-500">Serie determinista · Origen: simulated</p></div><div className="flex rounded-xl border border-slate-200 bg-white p-1" role="group" aria-label="Periodo del historial">{[["today","Hoy"],["7","7 días"],["30","30 días simulados"]].map(([value,label]) => <button key={value} className={`rounded-lg px-3 py-2 text-xs font-bold ${period === value ? "bg-forest-600 text-white" : "text-slate-600 hover:bg-slate-50"}`} onClick={() => setPeriod(value as typeof period)}>{label}</button>)}</div></div><ChartFrame title="Potencia, temperatura y humedad" description="Las escalas se muestran juntas solo para observar tendencias" empty={chartData.length === 0}><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="time" fontSize={10} minTickGap={28}/><YAxis fontSize={11}/><Tooltip/><Legend/><Line isAnimationActive={false} dataKey="potencia" name="Potencia W" stroke="#16815f" dot={false} strokeWidth={2}/><Line isAnimationActive={false} dataKey="temperatura" name="Temperatura °C" stroke="#e5a30f" dot={false}/><Line isAnimationActive={false} dataKey="humedad" name="Humedad %" stroke="#2a84c6" dot={false}/></LineChart></ResponsiveContainer></ChartFrame></div>
      <aside className="space-y-4"><article className="panel p-5"><div className="flex items-center gap-2"><RadioTower className={snapshot.nodeOnline ? "text-forest-600" : "text-slate-500"}/><h2 className="font-bold">Nodo</h2></div><p className="mt-3 text-sm font-semibold">{snapshot.nodeOnline ? "Conectado en modo demo" : "Desconectado"}</p><p className="mt-1 text-xs leading-5 text-slate-500">Última actualización: {formatDateTime(snapshot.recordedAt)}</p></article><article className="panel p-5"><h2 className="font-bold">Actividad y supuestos</h2><dl className="mt-3 space-y-3 text-sm"><div className="flex justify-between gap-3"><dt className="text-slate-500">Actividad</dt><dd className="font-semibold">{snapshot.presenceDetected ? "Detectada" : "No detectada"}</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Sin actividad</dt><dd className="font-semibold">{snapshot.minutesWithoutActivity} min</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Tarifa</dt><dd className="font-semibold">Bs {config.electricityTariffBs}/kWh</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Ahorro potencial</dt><dd className="font-semibold">Bs {formatNumber(potentialMonthly * config.electricityTariffBs)}/mes</dd></div></dl></article></aside></section>
    <section className="grid gap-6 lg:grid-cols-2"><article className="panel p-5"><h2 className="flex items-center gap-2 font-bold"><Activity className="h-5 w-5 text-danger-500"/>Alertas de la zona</h2>{environmentAlerts.length ? <ul className="mt-4 space-y-3">{environmentAlerts.map((alert) => <li key={alert.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><p className="font-bold">{alert.title}</p><span className="text-xs font-bold uppercase text-slate-500">{alert.status === "new" ? "Nueva" : alert.status === "acknowledged" ? "Reconocida" : "Cerrada"}</span></div><p className="mt-1 text-sm text-slate-600">{alert.description}</p></li>)}</ul> : <p className="mt-4 rounded-xl border border-dashed border-slate-300 p-5 text-sm text-slate-500">No hay alertas para esta zona.</p>}</article><article className="panel p-5"><h2 className="flex items-center gap-2 font-bold"><Clock3 className="h-5 w-5 text-forest-600"/>Recomendaciones</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-600"><li>• Comprobar si los equipos deben seguir encendidos cuando no se detecta actividad.</li><li>• Contrastar condiciones ambientales con instrumentos profesionales.</li><li>• Revisar hábitos familiares antes de cambiar rutinas de uso.</li></ul></article></section>
  </div>;
}
