import { motion } from "framer-motion";
import { ArrowRight, BarChart3, BellRing, Building2, CircleDollarSign, GraduationCap, HeartHandshake, Leaf, RadioTower, SlidersHorizontal, Users } from "lucide-react";
import { Link } from "react-router-dom";

export function HomePage() {
  return <div className="space-y-8">
    <section className="relative overflow-hidden rounded-3xl bg-forest-900 px-6 py-10 text-white sm:px-10 sm:py-14 lg:grid lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:gap-12">
      <div className="relative z-10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-300">Tecnología ambiental · Tarija</p><h1 className="mt-4 max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">Convertimos el desperdicio en <span className="text-emerald-300">ahorro</span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-emerald-50">Monitoreo inteligente para reducir gastos y cuidar los recursos, explicado con alertas y recomendaciones fáciles de comprender.</p>
        <div className="mt-8 flex flex-wrap gap-3"><Link className="button-primary bg-white text-forest-800 hover:bg-emerald-50" to="/simulador">Probar simulador <ArrowRight className="h-4 w-4" /></Link><Link className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/30 px-4 py-2.5 text-sm font-bold hover:bg-white/10" to="/instalacion">Ver instalación</Link><Link className="inline-flex min-h-11 items-center gap-2 px-3 text-sm font-bold text-emerald-200 hover:text-white" to="/dashboard">Abrir dashboard</Link></div>
      </div>
      <motion.div className="relative mt-10 lg:mt-0" initial={{ opacity: 0, scale: .95 }} animate={{ opacity: 1, scale: 1 }}><div className="rounded-3xl border border-white/15 bg-white/10 p-5 backdrop-blur"><div className="mb-4 flex items-center justify-between"><span className="font-bold">Bloque A</span><span className="rounded-full bg-emerald-300/20 px-2.5 py-1 text-xs font-bold text-emerald-200">En línea</span></div><div className="grid grid-cols-2 gap-3">{[["Aula 01","Normal"],["Aula 02","Revisar"],["Laboratorio","Activo"],["Oficina","Sin conexión"]].map(([name,status], index) => <div key={name} className="rounded-2xl bg-white/10 p-4"><div className={`mb-3 h-2 w-2 rounded-full ${index === 1 ? "bg-amber-300" : index === 3 ? "bg-slate-400" : "bg-emerald-300"}`} /><p className="text-sm font-bold">{name}</p><p className="mt-1 text-xs text-emerald-100">{status}</p></div>)}</div></div></motion.div>
    </section>
    <section className="grid gap-4 md:grid-cols-2"><article className="panel p-6"><p className="eyebrow">El problema</p><h2 className="mt-2 text-2xl font-bold">Pagamos sin ver dónde se desperdicia</h2><p className="mt-3 leading-7 text-slate-600">Muchas instituciones pagan sus facturas sin conocer en qué ambientes se producen consumos innecesarios.</p></article><article className="panel border-forest-100 bg-forest-50 p-6"><p className="eyebrow">Nuestra respuesta</p><h2 className="mt-2 text-2xl font-bold">Datos que se convierten en decisiones</h2><p className="mt-3 leading-7 text-slate-600">EcoAhorro convierte datos de consumo y condiciones del ambiente en alertas, recomendaciones y estimaciones fáciles de comprender.</p></article></section>
    <section><p className="eyebrow">Así funciona</p><h2 className="mt-2 text-3xl font-bold">De una lectura a una acción concreta</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{[
      [RadioTower,"1. Observar","Sensores y medidores adecuados registrarían condiciones del ambiente."],
      [SlidersHorizontal,"2. Interpretar","Reglas transparentes señalan condiciones que merecen revisión."],
      [BellRing,"3. Actuar","Una recomendación muestra el posible efecto antes de tomar una decisión."],
    ].map(([Icon,title,text]) => { const C = Icon as typeof RadioTower; return <article key={title as string} className="panel p-6"><C className="h-7 w-7 text-forest-600" /><h3 className="mt-4 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text as string}</p></article> })}</div></section>
    <section className="panel grid gap-8 p-6 md:grid-cols-2 lg:grid-cols-4"><div><GraduationCap className="h-6 w-6 text-tech-700"/><h3 className="mt-3 font-bold">Beneficiario directo</h3><p className="mt-1 text-sm text-slate-600">Estudiantes, docentes y personal.</p></div><div><Building2 className="h-6 w-6 text-tech-700"/><h3 className="mt-3 font-bold">Cliente pagador</h3><p className="mt-1 text-sm text-slate-600">La institución que gestiona sus gastos.</p></div><div><CircleDollarSign className="h-6 w-6 text-forest-600"/><h3 className="mt-3 font-bold">Impacto económico</h3><p className="mt-1 text-sm text-slate-600">Ahorro potencial y decisiones informadas.</p></div><div className="flex gap-4"><div><Leaf className="h-6 w-6 text-forest-600"/><h3 className="mt-3 font-bold">Impacto ambiental</h3><p className="mt-1 text-sm text-slate-600">CO₂ evitable estimado.</p></div><div><Users className="h-6 w-6 text-amber-700"/></div></div></section>
  </div>;
}
