import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowRight, Box, Building2, Cable, CheckCircle2, ClipboardCheck, Gauge, GraduationCap, Lightbulb, Pause, Play, RadioTower, RefreshCcw, Router, ShieldAlert, Thermometer, Wrench } from "lucide-react";

const steps = [
  { title: "Evaluar el edificio", component: "Plano del Bloque A", description: "Identificar ambientes, horarios y necesidades sin intervenir la instalación.", result: "Bloque A identificado", icon: Building2 },
  { title: "Seleccionar ambientes", component: "Aula, laboratorio y pasillo", description: "Priorizar espacios donde la información ayudaría a tomar decisiones.", result: "5 ambientes priorizados", icon: GraduationCap },
  { title: "Seleccionar puntos de medición", component: "Puntos seguros", description: "Definir dónde medir con criterios técnicos y de seguridad.", result: "Puntos definidos", icon: Gauge },
  { title: "Instalar visualmente el medidor", component: "Medidor adecuado", description: "En la demostración solo representamos su posición; no se manipula corriente alterna.", result: "Medidor representado", icon: Wrench },
  { title: "Ubicar los sensores", component: "Sensores ambientales", description: "Colocar sensores lejos de obstáculos y fuentes de calor directo.", result: "Sensores ubicados", icon: Thermometer },
  { title: "Conectar sensores al nodo", component: "Nodo EcoAhorro", description: "En la maqueta, los sensores de bajo voltaje envían datos simulados al nodo.", result: "Conexiones de datos trazadas", icon: Cable },
  { title: "Proteger el nodo", component: "Caja protectora", description: "Representar una caja que evita contacto y mantiene ordenada la instalación.", result: "Nodo protegido", icon: Box },
  { title: "Conectar el nodo a la red", component: "Red institucional", description: "El nodo enviaría lecturas a una fuente de datos; aquí se simula localmente.", result: "Enlace de red simulado", icon: Router },
  { title: "Registrar el ambiente", component: "Ficha de Aula 02", description: "Asociar el nodo con nombre, tipo y capacidad del ambiente.", result: "Aula 02 registrada", icon: ClipboardCheck },
  { title: "Probar las lecturas", component: "Panel de verificación", description: "Verificar unidades, origen del dato y respuesta ante desconexión.", result: "Lecturas simuladas válidas", icon: Lightbulb },
  { title: "Marcar como operativo", component: "Nodo EcoAhorro", description: "Finalizar la representación cuando las comprobaciones son correctas.", result: "Nodo operativo en modo demo", icon: CheckCircle2 },
];

function SchoolDiagram({ step }: { step: number }) {
  const activeRoom = Math.min(Math.max(step - 1, 0), 4);
  return <div className="relative min-h-[390px] overflow-hidden rounded-2xl border border-slate-200 bg-slate-50 p-5">
    <div className="mb-4 flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wide text-slate-500">Vista conceptual · Bloque A</span><span className="rounded-full bg-tech-50 px-2 py-1 text-xs font-bold text-tech-700">Sin cableado real</span></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{["Aula 01","Aula 02","Laboratorio","Pasillo","Oficina"].map((room, index) => <motion.div key={room} animate={{ borderColor: index === activeRoom ? "#16815f" : "#cbd5e1", backgroundColor: index === activeRoom ? "#effaf5" : "#ffffff" }} className={`relative min-h-24 rounded-xl border-2 p-3 ${room === "Pasillo" ? "sm:col-span-2" : ""}`}><span className="text-xs font-bold text-slate-700">{room}</span>{step >= 4 && index === 1 && <motion.div initial={{ y: -25, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className="absolute bottom-3 left-3 flex gap-2"><Thermometer className="h-5 w-5 text-amber-700"/><Lightbulb className="h-5 w-5 text-tech-700"/></motion.div>}{step >= 8 && index === 1 && <span className="absolute bottom-2 right-2 h-3 w-3 rounded-full bg-forest-500" />}</motion.div>)}</div>
    <div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-center"><Gauge className="mx-auto h-5 w-5 text-amber-700"/><p className="mt-1 text-xs font-bold">Punto de medición</p></div><motion.div className="h-1 w-full rounded bg-tech-500" initial={{ scaleX: 0 }} animate={{ scaleX: step >= 5 ? 1 : .2 }} transition={{ duration: .5 }} />
      <motion.div animate={{ scale: step >= 6 ? 1 : .9 }} className={`rounded-xl border p-3 text-center ${step >= 10 ? "border-forest-200 bg-forest-50" : "border-tech-200 bg-tech-50"}`}><RadioTower className={`mx-auto h-6 w-6 ${step >= 10 ? "text-forest-600" : "text-tech-700"}`} /><p className="mt-1 text-xs font-bold">Nodo EcoAhorro</p><p className="text-[11px] text-slate-500">{step >= 10 ? "Operativo · demo" : "Configurando"}</p></motion.div></div>
    {step >= 7 && <motion.div className="absolute bottom-8 right-8 flex gap-2" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>{[0,1,2].map((value) => <motion.span key={value} className="h-2 w-2 rounded-full bg-tech-500" animate={{ x: [0, 14, 28], opacity: [0, 1, 0] }} transition={{ duration: 1, delay: value * .18, repeat: 2 }} />)}</motion.div>}
  </div>;
}

export function InstallationPage() {
  const [step, setStep] = useState(0);
  const [playing, setPlaying] = useState(false);
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setStep((current) => { if (current >= steps.length - 1) { setPlaying(false); return current; } return current + 1; }), 1600); return () => window.clearInterval(timer); }, [playing]);
  const current = steps[step];
  const Icon = current.icon;
  return <div className="space-y-6"><header><p className="eyebrow">Recorrido guiado</p><h1 className="page-title mt-2">¿Cómo se instalaría EcoAhorro?</h1><p className="mt-3 max-w-3xl text-slate-600">Una explicación visual, segura y no técnica. Esta etapa no conecta equipos ni interviene instalaciones eléctricas.</p></header>
    <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><div className="panel p-5"><SchoolDiagram step={step} /></div><div className="panel flex flex-col p-5"><div className="flex items-center justify-between"><span className="eyebrow">Paso {step + 1} de {steps.length}</span><span className="text-xs font-bold text-slate-500">{Math.round(((step + 1) / steps.length) * 100)}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><motion.div className="h-full rounded-full bg-forest-500" animate={{ width: `${((step + 1) / steps.length) * 100}%` }} /></div>
      <AnimatePresence mode="wait"><motion.div key={step} initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }} className="mt-8"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-forest-50 text-forest-700"><Icon /></span><h2 className="mt-4 text-2xl font-bold">{current.title}</h2><p className="mt-2 leading-7 text-slate-600">{current.description}</p><dl className="mt-6 space-y-3 rounded-xl bg-slate-50 p-4 text-sm"><div><dt className="font-bold text-slate-500">Componente seleccionado</dt><dd className="mt-1 font-semibold">{current.component}</dd></div><div><dt className="font-bold text-slate-500">Resultado del paso</dt><dd className="mt-1 flex items-center gap-2 font-semibold text-forest-700"><CheckCircle2 className="h-4 w-4" />{current.result}</dd></div></dl></motion.div></AnimatePresence>
      <div className="mt-auto flex flex-wrap gap-2 pt-7"><button className="button-secondary" disabled={step === 0} onClick={() => setStep((value) => value - 1)}><ArrowLeft className="h-4 w-4" />Anterior</button><button className="button-primary" disabled={step === steps.length - 1} onClick={() => setStep((value) => value + 1)}>Siguiente<ArrowRight className="h-4 w-4" /></button><button className="button-secondary" onClick={() => setPlaying((value) => !value)}>{playing ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}{playing ? "Pausar" : "Reproducir"}</button><button aria-label="Reiniciar recorrido" className="button-secondary px-3" onClick={() => { setStep(0); setPlaying(false); }}><RefreshCcw className="h-4 w-4" /></button></div></div></section>
    <section className="grid gap-4 md:grid-cols-2"><article className="panel p-5"><p className="eyebrow">Maqueta de demostración</p><h2 className="mt-2 font-bold">Sensor de bajo voltaje y datos simulados</h2><p className="mt-2 text-sm leading-6 text-slate-600">El INA219 solo se representa como componente para una maqueta de corriente continua. El MQ-135 no reemplaza un equipo profesional de medición ambiental.</p></article><article className="panel border-tech-100 bg-tech-50 p-5"><p className="eyebrow text-tech-700">Instalación futura</p><h2 className="mt-2 font-bold">Medidor adecuado, caja protectora e instalación profesional</h2><p className="mt-2 text-sm leading-6 text-slate-600">Una implementación real requeriría equipos certificados para corriente alterna y evaluación técnica del sitio.</p></article></section>
    <div className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0"/><p><strong>Seguridad:</strong> La instalación eléctrica real debe ser realizada por personal capacitado y utilizando medidores adecuados para corriente alterna. Esta vista no incluye instrucciones de cableado doméstico.</p></div>
  </div>;
}
