import { CalendarDays, FileText, Leaf, Printer, TriangleAlert } from "lucide-react";
import { useApp } from "../app/AppProvider";
import { Disclaimer } from "../components/Disclaimer";
import { environments } from "../data/mockData";
import { formatNumber } from "../utils/format";

export function ReportsPage() {
  const { alerts, config } = useApp();
  const active = alerts.filter((alert) => alert.status !== "closed");
  const avoidableEnergy = 22.9;
  const generatedAt = new Intl.DateTimeFormat("es-BO", { dateStyle: "long", timeStyle: "short" }).format(new Date());
  return <div className="space-y-6"><header className="no-print flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Documento interno</p><h1 className="page-title mt-2">Reporte de desempeño</h1><p className="mt-3 text-slate-600">Vista imprimible del escenario demostrativo institucional.</p></div><button className="button-primary" onClick={() => window.print()}><Printer className="h-4 w-4"/>Imprimir reporte</button></header>
    <article className="print-panel panel mx-auto max-w-5xl overflow-hidden"><div className="bg-forest-900 p-6 text-white sm:p-8"><div className="flex items-start justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">EcoAhorro IoT</p><h2 className="mt-2 text-3xl font-bold">Reporte de desempeño EcoAhorro</h2><p className="mt-2 text-emerald-100">Colegio Eco Tarija · Escenario demostrativo</p></div><FileText className="hidden h-10 w-10 text-emerald-300 sm:block"/></div></div>
      <div className="space-y-8 p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs font-bold uppercase text-slate-500">Institución</p><p className="mt-1 font-bold">Colegio Eco Tarija</p><p className="text-sm text-slate-600">Colegio privado · Tarija</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Periodo</p><p className="mt-1 font-bold">Últimos 30 días simulados</p><p className="text-sm text-slate-600">Agosto de 2026</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Generado</p><p className="mt-1 font-bold">{generatedAt}</p><p className="text-sm text-slate-600">Documento interno demostrativo</p></div></div>
        <section><h3 className="text-lg font-bold">Resumen estimado</h3><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-forest-50 p-4"><Leaf className="h-5 w-5 text-forest-600"/><p className="mt-2 text-2xl font-bold">{formatNumber(avoidableEnergy)} kWh</p><p className="text-sm text-slate-600">Energía evitable estimada</p></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-2xl font-bold">Bs {formatNumber(avoidableEnergy * config.electricityTariffBs)}</p><p className="mt-1 text-sm text-slate-600">Ahorro potencial</p></div><div className="rounded-xl bg-tech-50 p-4"><p className="text-2xl font-bold">{formatNumber(avoidableEnergy * config.emissionFactorKgPerKwh)} kg CO₂</p><p className="mt-1 text-sm text-slate-600">CO₂ evitable estimado</p></div></div></section>
        <section><h3 className="text-lg font-bold">Desempeño por ambiente</h3><div className="mt-3 overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Ambiente</th><th className="p-3">Condición</th><th className="p-3">Alertas activas</th><th className="p-3">Recomendación</th></tr></thead><tbody className="divide-y divide-slate-100">{environments.map((environment) => <tr key={environment.id}><td className="p-3 font-bold">{environment.name}</td><td className="p-3">{environment.status === "normal" ? "Normal" : environment.status === "offline" ? "Nodo desconectado" : "Requiere revisión"}</td><td className="p-3">{active.filter((alert) => alert.environmentId === environment.id).length}</td><td className="p-3 text-slate-600">{environment.status === "normal" ? "Mantener monitoreo" : environment.status === "offline" ? "Revisar conectividad" : "Revisar equipos y horarios"}</td></tr>)}</tbody></table></div></section>
        <section className="grid gap-6 sm:grid-cols-2"><div><h3 className="font-bold">Supuestos</h3><ul className="mt-3 space-y-2 text-sm text-slate-600"><li>• Tarifa: Bs {config.electricityTariffBs}/kWh.</li><li>• Factor: {config.emissionFactorKgPerKwh} kg CO₂/kWh.</li><li>• Periodo escolar: 22 días/mes.</li><li>• Dos horas potencialmente evitables por día.</li></ul></div><div><h3 className="font-bold">Alertas y recomendaciones</h3><p className="mt-3 text-sm leading-6 text-slate-600">Se registraron {active.length} alertas activas simuladas. Se recomienda revisar iluminación fuera de horario, equipos encendidos sin actividad y conectividad de nodos.</p></div></section>
        <div className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><TriangleAlert className="mt-0.5 h-5 w-5 shrink-0"/><p>Este reporte es una herramienta interna demostrativa; no corresponde a una auditoría ni presenta resultados de una institución real.</p></div><Disclaimer className="print:block" />
      </div></article>
  </div>;
}
